version: "3"
virtualbrowsers:
- name: rhd-login
  url: https://developers.redhat.com/node/284339?auHash=5k9QV-yD0z-jAU7XkJyq1TUxhVyyZVLiuZz7tsfTz_s&offerid=3881844
virtualmachines:
- name: crc
  image: rhd-devx-instruqt/openshift-4-12-1-rwwzd
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
